name: arceus
description: A sample command-line application with basic argument parsing.
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  ansix: ^0.3.3
  dart_console: ^1.2.0
  uuid: any
  archive: ^3.6.1
  cli_spin: ^1.0.1
  chalkdart: ^2.2.1
  interact: ^2.2.0
  lua_dardo: ^0.0.5
  hashlib: ^1.21.0
  logger: ^2.5.0
  talker: ^4.5.1
  ffi: ^2.1.3
  open_url: ^2.0.1
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^16.0.0

ffigen:
  # Run with `flutter pub run ffigen --config ffigen.yaml`.
  name: SquirrelBindings
  description: |
    Bindings for `src/squirrel3/include/squirrel.h`.

    Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
  output: "lib/scripting/squirrel_bindings_generated.dart"
  headers:
    entry-points:
      - "src/squirrel3/include/squirrel.h"
    include-directives:
      - "src/squirrel3/include/squirrel.h"
  preamble: |
    // ignore_for_file: always_specify_types
    // ignore_for_file: camel_case_types
    // ignore_for_file: non_constant_identifier_names
  comments:
    style: any
    length: full
  ignore-source-errors: true
  silence-enum-warning: true
  structs:
    rename:
      "_(.*)": "$1" # Removes prefix underscores from all structures.
