name: arceus
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  ansix: ^0.3.3
  dart_console: ^1.2.0
  uuid: ^4.4.2
  archive: ^3.6.1
  cli_spin: ^1.0.1
  dart_eval: ^0.7.9
  hetu_script: ^0.3.12
  terminal_decorate: ^0.3.0
  interact: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
