name: arceus
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  yaml: ^3.1.2
  ansix: ^0.3.3
  dart_console: ^1.2.0
  uuid: any
  archive: ^3.6.1
  cli_spin: ^1.0.1
  chalkdart: ^2.2.1
  interact: ^2.2.0
  lua_dardo: ^0.0.5
  hashlib: ^1.21.0
  logger: ^2.5.0
  talker: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
