name: Build

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.5
      - name: Fetch Dependencies
        run: dart pub get .
      - name: Make Build Directories
        run: "mkdir -p build/releases/${{ matrix.platform }} ||
          mkdir -p ./scripts/installers/${{ matrix.platform }}/lib"
      - name: Build Executable
        run: dart compile exe ./lib/main.dart --target-os ${{ matrix.platform }} -o build/releases/${{ matrix.platform }}/${{ matrix.output}}
      - name: Build Squirrel
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: ./src/squirrel3/
          build-dir: ./src/squirrel3/
      - name: Adding files to Artifact
        run:
          "cp -r ./src/squirrel3/ ./scripts/installers/${{ matrix.platform }}/lib/ &&
          cp -r ./scripts/installers/${{ matrix.platform }}/ build/releases/${{ matrix.platform }}/"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: build/releases/${{ matrix.platform }}/
          retention-days: 14
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            output: arceus.elf
            library-extension: so
          - os: windows-latest
            platform: windows
            output: arceus.exe
            library-extension: dll
          - os: macos-latest
            platform: macos
            output: arceus.app
            library-extension: dylib
