name: Build

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.5
      - name: Fetch Dependencies
        run: dart pub get .
      - name: Make Build Directories
        run: mkdir -p build/releases/${{ matrix.platform }}
      - name: Build
        run: dart compile exe ./bin/main.dart --target-os ${{ matrix.platform }} -o build/releases/${{ matrix.platform }}/${{ matrix.output }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: build/releases/${{ matrix.output }}
          retention-days: 14
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            output: arceus.elf
          - os: windows-latest
            platform: windows
            output: arceus.exe
          - os: macos-latest
            platform: macos
            output: arceus.app
