name: Build

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.5
      - name: Fetch Dependencies
        run: dart pub get .
      - name: Make Build Directories
        run: mkdir -p build/releases
      - name: Build
        run: dart compile exe ./bin/main.dart --target-os ${{ matrix.platform }} -o ${{ matrix.output }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.output }}
          retention-days: 14

      - name: Update MudkiPC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/Pokemon-Manager/MudkiPC.git
          cd MudkiPC
          ls
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout main
          git pull
          cd assets
          cd arceus
          mkdir -p ${{ matrix.platform }}
          cd ${{ matrix.platform }}
          cp -r ../../../../${{ matrix.output }}
          git commit -m "Update Arceus"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            output: build/releases/arceus.elf
          - os: windows-latest
            platform: windows
            output: build/releases/arceus.exe
          - os: macos-latest
            platform: macos
            output: build/releases/arceus.app
